# Site settings
title: PU5JNP - Thiago Paes - Radioamador
email: contato@pu5jnp.qsl.br
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://pu5jnp.qsl.br/" # the base hostname & protocol for your site
domain: pu5jnp.qsl.br

instagram_username: pu5jnp
github_username: mrprompt

# Build settings
markdown: kramdown
